spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/jboot_gonnys?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: gonnys
    password: 12345678
    
    
  jpa:
    hibernate:
      ddl-auto: update #삭제는 create-drop, 업데이트 update
        
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
      
        